use_frameworks!

target 'SegmentedProgressView_Example' do
  pod 'SegmentedProgressView', :path => '../'

  target 'SegmentedProgressView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
